#!/bin/bash
"""This script configures web-02 to be identical to web-01"""
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom HTTP response header
sudo sed -i 's/# server_tokens off;/add_header Test "This a custom header";\n        server_tokens off;/' /etc/nginx/nginx.conf

# Reload Nginx
sudo service nginx reload

