#!/usr/bin/env bash
#This script configures a server to listen to port 80
#Delete the existing ../sites-enabled/default
#replace it with a copy of ../sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
